### ISSUE TITLE
Why http proxy port is always changing

### ISSUE THREAD

**Issue by CodingPapi** [zjx20/socks-cli#4]
Can we use a fixed port as http/https proxy port?
Thanks!

**Comment by zjx20** [comment]
The http proxy is not a global background service. When you activate socks-cli on a shell, a dedicated http proxy will be started, and will be killed if the shell died. That means socks-cli is isolated from different shell windows.

In this design, if a fixed port number was used, we can't activate socks-cli on the second shell window because it can't listen on the same port.

Although it's not recommended, your problem can be solved by starting a global http proxy server by hand:
```bash
cd socks-cli/py/socks2http
python socks2http.py --port 8080 --socks-server "localhost:1080" &
```

**Comment by CodingPapi** [comment]
thanks!
